### ISSUE TITLE
cache saves are suddenly failing

### ISSUE THREAD

**Issue by eedwards-sk** [vito/oci-build-task#13]
```
#24 writing layer sha256:df25d6379e2e96da40fd486dd27cada82f981297576999c97e5b49eecab92e76
#24 writing layer sha256:df25d6379e2e96da40fd486dd27cada82f981297576999c97e5b49eecab92e76 0.4s done
#24 writing config sha256:0d0f44b862a9954cdaee2e3260da9469a23407182218a44db36f853c1c1b7109
ERRO[0090] (*service).Write failed                       error="rpc error: code = Canceled desc = context canceled" expected="sha256:781c81f1712469207aa8d56967b55cfd67986c9aadf5d80e8d4d7ae4f933b1c0" ref="sha256:781c81f1712469207aa8d56967b55cfd67986c9aadf5d80e8d4d7ae4f933b1c0" total=3290
#24 writing config sha256:0d0f44b862a9954cdaee2e3260da9469a23407182218a44db36f853c1c1b7109 0.0s done
#24 writing manifest sha256:781c81f1712469207aa8d56967b55cfd67986c9aadf5d80e8d4d7ae4f933b1c0 0.0s done
#24 DONE 1.7s
```

The cache is no-longer being used on follow-up builds, being re-built every time, so I suspect the above error may be related.

Starting with an issue here, in case it's common among concourse users, or an issue specific to concourse.

**Comment by eedwards-sk** [comment]
and just as quickly as it came, the problem disappeared... didn't see the error this time, and the cache was reused... /shrug

**Comment by eedwards-sk** [comment]
Okay, still seeing issues where the cache isn't being used, regularly.

**Comment by eedwards-sk** [comment]
and yet again, on a build where USING the cache failed, I also see an error as per above.

**Comment by eedwards-sk** [comment]
So the error must be a red herring, but I'm still getting super inconsistent cache behavior.

Local docker cached builds work fine and will re-use layers.

My build task is simple:

```
---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task

params:
  CONTEXT: source-repo

inputs:
- name: source-repo

outputs:
- name: image

caches:
- path: cache

run:
  path: build
```

and I do see the cache work sometimes, but now it seems to almost never be using cached layers

I only have one worker and it hasn't been re-created in a while, so I assume the cache should be available.
