### ISSUE TITLE
Support insecure registries in FROM

### ISSUE THREAD

**Issue by vito** [vito/oci-build-task#3]
Looks like this is possible by configuring `buildkitd` like so:

```toml
[registry."some-registry.example.com"]
http = true
```

However I have the same concerns as with #2 - should we encourage folks to use the `registry-image` resource for fetching these instead once #1 is done?
