### ISSUE TITLE
Cannot hijack task container that is based on oci-build-task

### ISSUE THREAD

**Issue by holgerstolzenberg** [vito/oci-build-task#49]
Problem described in summary.

Task file:
```yaml
---
platform: linux

inputs:
  - name: pull-request
    path: .

image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
    tag: 0.4.0

caches:
  - path: cache

run:
  path: build
```

When the task failed I tried to `hijack` the container and git this:

<img width="1765" alt="Screenshot 2020-12-10 at 13 30 02" src="https://user-images.githubusercontent.com/282736/101773125-a4697680-3aec-11eb-876b-89eb13196a1b.png">

Looks like `bash` is missing in `$PATH`
