### ISSUE TITLE
How to use the --secret flag from the build-image job

### ISSUE THREAD

**Issue by anouarchattouna** [vito/oci-build-task#53]
Hello,

I am wondering how to use the `--secret` flag for [docker build](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information) in a concourse `build-image` job.

For example, we have to copy a file from an `aws s3` bucket to the docker image, for that we pass the credentials to the docker build phase using the `--secret` flag like described from this [link](https://docs.docker.com/develop/develop-images/build_enhancements/#new-docker-build-secret-information):
```
RUN --mount=type=secret,id=aws,target=/root/.aws/credentials aws s3 cp s3://... ...
```
```
$ docker build --secret id=aws,src=$HOME/.aws/credentials .
```

=> How to integrate that in the `build-image` job
```
jobs:
  - name: build-image
    serial: true
    plan:
      - get: repo
        trigger: true
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          params:
            DOCKERFILE: images/Dockerfile
            CONTEXT: images
          inputs:
            - name: repo
              path: .
          outputs:
            - name: image
  ```
FYI, this PR https://github.com/vito/oci-build-task/pull/34 is implementing a similar feature but for the `--ssh` flag.

Best,
